[package]
name = "lang2c"
version = "0.1.0"
edition = "2021"
description = "Lang2 compiler driver"

[dependencies]
lang2-ast = { path = "../../src/lang2-ast" }
lang2-parser = { path = "../../src/lang2-parser" }

bumpalo = "3.14.0"
clap = { version = "4.4.6", features = ["derive"] }
once_cell = "1.18.0"
serde_json = "1.0.107"
