[package]
name = "lang2test"
version = "0.1.0"
edition = "2021"
description = "Lang2 test suite runner"

[dependencies]
lang2-ast = { path = "../../src/lang2-ast" }
lang2-parser = { path = "../../src/lang2-parser" }

bumpalo = "3.14.0"
serde_json = "1.0.107"
serde = { version = "1.0.188", features = ["derive"] }
clap = { version = "4.4.6", features = ["derive"] }
tempfile = "3.8.0"
owo-colors = "3.5.0"
